### ISSUE TITLE
No presets available, all costs default to 0

### ISSUE THREAD

**Issue by keyspace** [linuxgurugamer/KRASH#10]
`Player.log` is spammed with:

```
File '<path-to-ksp>/KSP_Data/../GameData/KRASH/PluginData/KRASH.cfg' does not exist
File '<path-to-ksp>/KSP_Data/../GameData/KRASH/PluginData/KRASHCustom.cfg' does not exist
```

`<path-to-ksp` is `/home/keyspace/.local/share/Steam/steamapps/common/Kerbal Space Program` - replaced for readability.

Obviously, creating the folder and moving configs there fixes the issue.

System:
- `Arch Linux 64-bit`;
- `KSP 1.1.3`;
- `KRASH 0.5.18`;
- lots of other mods, can list if needed;
- installed through `CKAN v0.07-3620-g2335045` (dated git).

Need confirmation whether this is a deployment issue.

**Comment by linuxgurugamer** [comment]
Bad release, fixing now
