### ISSUE TITLE
Orbit parameters are changed when going to time-warp if sim is stared not from Kerbin

### ISSUE THREAD

**Issue by stasikos** [linuxgurugamer/KRASH#15]
I'm using Linux 64-bit 1.2.1 KSP and KRASH v0.5.22.1.
Steps to reproduce: 
get stock Sandbox game, load "Super-heavy lander" into VAB and launch simulation on 20km Mun orbit. Press '>' button to make time faster. Note if Mun surface starts jumping when you enter into physicless time-warp mode.

Terminate simulation and start it again from Launchpad. Use stock cheat menu to jump ship to Mun orbit. Repeat timewarp. Do you see any difference?

For me it jumps forward relative to Mun on every time it goes to on-rails mode, but only when simulation is started not from Launchpad. Altitude is not changed, even if you are descending when landing, so it is not just time-acceleration. It looks like argument of periapsis is changing or something like it. You can stop timewarp and try again many times in a row and see those jumps. 
It not depends on Mun itself, any planet/moon works. The only body I'm in doubt is Kerbin, because nothing like it observed here.

Logs (first flight started on Mun orbit, second is from Launchpad, as described above).
https://dl.dropboxusercontent.com/u/5113976/KSP/ziplogsKRASH.zip

P.S. Even more noticeable effect:
Start simulating same lander landed on Mun. Takeoff, ascend to 5km, enable time warp. It will jump about 80 degree longitude towards east around Mun.

**Comment by kamalmostafa** [comment]
I experience this problem too.  As a work-around, you can set the orbit manually from the Meta-F12 cheat menu after starting the simulation.

Example:  Start a KRASH simulation in Mun orbit (say at 25km).  Press Meta-F12, select the "Set Orbit" panel, enter values SMA=225000 Eccentricity=0.0001 and all the rest zero  (Note 225000 = Mun radius 200km + 25km).  Click Set Orbit, close the F12 window.  Now this KRASH simulation session will time-warp without exhibiting the problem.

It looks to me like commit 1af85b2c0e9594928eea12bec9ea42096295d84f (or at least the code it touches) may be related to this problem.  But note that that **setting the Eccentricity value to a non-zero value appears to be critical here** -- not what that commit does.

**Comment by Dunbaratu** [comment]
I can verify it was happening to me just today.  Since it was while I was testing a kOS script that was all about targeting a specific landing site, the tendency of the ship to jump about 10 degrees of longitude forward whenever I time warped made this test pretty much impossible to carry out in the simulator.

**Comment by linuxgurugamer** [comment]
Just an FYI, I'm experiencing the same timewarp issue without KRASH installed, so I'm pretty sure it's not KRASH doing it.
I'll let you know if I can finally isolate the mod which is doing it

**Comment by LPGhatguy** [comment]
Any new findings on this? I just added KRASH to my game (1.4.4) today and started hitting this issue too, I haven't seen anything like it before!

**Comment by RaynorD** [comment]
I am still experiencing this bug in both in my main 1.4.5 game and a fresh 1.5.1 install with only KRASH, ClickThroughToolbar, and ToolbarControl installed. I am simulating a crewed Mk1 Command Pod at Duna at 75km. The distance it jumps appears to be linearly related to MET, starting at 0 and up to around 45 degrees at T+1 hour. At warp start, the craft jumps forward in the orbit, but the orbit fade start point stays in the correct place, gradually falling behind the craft. When the warp is stopped it then jumps ahead to meet the craft.  
https://i.imgur.com/YG92Nas.jpg  
https://i.imgur.com/K3iGfzj.jpg

Versions:
- KRASH: 0.5.29.2
- ClickThroughBlocker: 0.1.6.9
- ToolbarControl: 0.1.6.18 

Windows 10

1.5.1 Log: https://pastebin.com/WTDuYhbV

**Comment by JonnyOThan** [comment]
I’m experimenting with a change to use FlightGlobals.SetShipOrbit which seems to fix this and lots of other annoying issues.

**Comment by linuxgurugamer** [comment]
> I’m experimenting with a change to use FlightGlobals.SetShipOrbit which seems to fix this and lots of other annoying issues.

Any progress with this?

**Comment by kallezz** [comment]
This is still an issue with KRASH 0.5.33.4 in KSP 1.12.2
