### ISSUE TITLE
FEATURE REQUEST: Disable TestFlight on Sims

### ISSUE THREAD

**Issue by pap1723** [linuxgurugamer/KRASH#19]
Hi @linuxgurugamer !

I have a request that comes in from the RO community. The Test Flight mod is integral for the properRO experience, but it is very annoying to have an engine fail during a simulation to make sure your craft is built correctly. Would you be able to add some code to disable Test Flight during KRASH sims?

Test Flight has a GUI with options that allows you to disable it anytime, so you might be able to hook into that.

Thanks
Pap

**Comment by linuxgurugamer** [comment]
I'll have to look at Testflight to see if there is an API to hook into.

**Comment by siimav** [comment]
This was implemented in #21
