### ISSUE TITLE
FEATURE REQUEST: Custom Default Starting Orbits

### ISSUE THREAD

**Issue by 7ranceaddic7** [linuxgurugamer/KRASH#20]
Couldn't find anything in your code that specified the default starting altitude (Kerbin = 70100) for orbital sims.  So, I imagine you are pulling them from somewhere.

Personally, use a parking orbit of 100km for all launches at Kerbin.  Is there some way to make this the default altitude?  Is there a MM_config I can create/use to set this parameter? 

(You can tell me to stop being so damn lazy and just bugger-off.)

**Comment by linuxgurugamer** [comment]
I'm pretty sure the default orbit is 100+minimum orbital altitude, but you can change that.  There is no default which can be specified, but I'll add it as a feature request

**Comment by linuxgurugamer** [comment]
Added, will be released tomorrow, I hope

**Comment by linuxgurugamer** [comment]
Released

**Comment by 7ranceaddic7** [comment]
Wow!!!  That was head-spinningly fast.  Thanks so much.

**Comment by linuxgurugamer** [comment]
It was head-spinningly easy :-)

Your welcome
