### ISSUE TITLE
Don't pay more for time warp

### ISSUE THREAD

**Issue by Dunbaratu** [linuxgurugamer/KRASH#23]
The per-minute costs of simulating are based on the in-game-universe time rather than the out-of-game wall clock, which feels a bit unfair when time warping.  When time warping at, say, 1000x, you are paying 1000 times the rate in funds for the simulation, when if it is a simulation you'd expect that it's not doing expensive computer work during that time (just like the KSP game itself isn't - as most physics rules are turned off during time warp).

I think fixing this might make issue #22 moot as well, as it would mean you're not penailzed on cost for just time warping the simulation forward a few days.

One thing that would complicate this is that when you pause the game and walk away from it, the wall clock keeps going forward, which would make simulation on the wall clock unfair.  So it can't just be on the wall clock, it has to be on the wall clock *except* for the time spent with the game paused.

It would mean people with slow computers pay slightly more to simulate (when their frame rate is bad enough that it takes more than 1 second to simulate 1 second of game time), but that would be a small difference compared to the current unfair cost of doing time warp.

**Comment by linuxgurugamer** [comment]
Interesting, I'll have to think about how to do it.

**Comment by ShadyWalker** [comment]
Is there a way to check each time it increments the sim cost if time warp is enabled and not add to the cost if it is true?

**Comment by ShadyWalker** [comment]
I don't know much about programming in C, but I made a fork and modified what I think will address this enhancement request.  I don't know if it will compile correctly or not, but it is posted on github in case it works...

**Comment by ShadyWalker** [comment]
I went into the new build for KRASH and I think after some detailed analysis, that the only line that needs adjusted for this timewarp request to be added is to change line 105 of APIManager.cs to "KRASHShelter.simCost += (cost / TimeWarp.CurrentRate);" There are other references to the value throughout the code, but it only gets incremented in that one spot that I can find. I would make a merge request with the change already done, but I do not know enough to be able to get it to build apparently.
