### ISSUE TITLE
Simulation button doesn't appear in VAB or SPH

### ISSUE THREAD

**Issue by TruePikachu** [linuxgurugamer/KRASH#25]
[KSP.log](https://github.com/linuxgurugamer/KRASH/files/1712235/KSP.log)

Right now, while I get the configuration button in the main space center scene, I _don't_ get any button in either the VAB or SPH scenes to actually configure+start a simulation. When I have time, I'll see if I can reduce to a minimum mod configuration.

**Comment by TruePikachu** [comment]
Janitor's Closet appears to be the culprit. No, the simulation button isn't hidden in JC's own menu :)

**Comment by linuxgurugamer** [comment]
If it's JC, then open an issue there
Thanks
