### ISSUE TITLE
Vessel jumps in orbit when time warping

### ISSUE THREAD

**Issue by tivec** [linuxgurugamer/KRASH#26]
Hello! Whenever I simulate a flight and time warp, the vessel jumps forward in orbit as if skipping several minutes. See this video:

http://i.tivec.org/2018-03-29_10-01-51.mp4

Should be mentioned this is on 1.4.2, running KRASH 0.5.28.

**Comment by tivec** [comment]
Some more details from my testing: I thought this had a relation to either Kerbal Joint Reinforcement or BetterTimeWarp. Removing those seems to have shortened the jump distance somewhat, but it is still skipping time.

**Comment by linuxgurugamer** [comment]
Does it happen in 1.4.1?

**Comment by tivec** [comment]
I do not remember this happening in 1.4.1, so it is possible it is related to the .2 update.

**Comment by OrbitalManeuvers** [comment]
BTW and KJR are likely red herrings. I've never used either and this happens to me.

**Comment by JonnyOThan** [comment]
This seems like a dupe of #15

**Comment by linuxgurugamer** [comment]
Fixed by PR
