### ISSUE TITLE
SIM not showing up in VAB

### ISSUE THREAD

**Issue by MrJadaml** [linuxgurugamer/KRASH#29]
SIM is not showing up in the VAB. Here are some relevant logs from KSP.log

```
AssemblyLoader: Loading assembly at /Users/foo/Library/Application Support/Steam/steamapps/common/Kerbal Space Program/GameData/KIS/Plugins/MiniAVC.dll
[LOG 11:48:10.706] Load(Assembly): KRASH/MiniAVC
[LOG 11:48:10.706] AssemblyLoader: Loading assembly at /Users/foo/Library/Application Support/Steam/steamapps/common/Kerbal Space Program/GameData/KRASH/MiniAVC.dll
[LOG 11:48:10.707] Load(Assembly): KRASH/Plugins/KRASH
[LOG 11:48:10.707] AssemblyLoader: Loading assembly at /Users/foo/Library/Application Support/Steam/steamapps/common/Kerbal Space Program/GameData/KRASH/Plugins/KRASH.dll
[LOG 11:48:10.709] AssemblyLoader: KSPAssemblyDependency 'ToolbarController' V1.0.0
[LOG 11:48:10.709] AssemblyLoader: KSPAssemblyDependency 'ClickThroughBlocker' V1.0.0
[LOG 11:48:10.709] AssemblyLoader: KSPAssemblyDependency 'ToolbarController' V1.0.0
[LOG 11:48:10.709] Load(Assembly): KerbalEngineer-1.1.5.3/KerbalEngineer/KerbalEngineer.Unity
...
[LOG 11:48:10.751] AssemblyLoader: Loading assemblies
[WRN 11:48:10.752] AssemblyLoader: Assembly 'KRASH' has not met dependency 'ToolbarController' V1.0.0
[WRN 11:48:10.752] AssemblyLoader: Assembly 'KRASH' has not met dependency 'ClickThroughBlocker' V1.0.0
[WRN 11:48:10.752] AssemblyLoader: Assembly 'KRASH' has not met dependency 'ToolbarController' V1.0.0
[WRN 11:48:10.752] AssemblyLoader: Assembly 'KRASH' is missing 3 dependencies
```

```
[LOG 11:48:16.501] Load(Texture): KRASH/Textures/KRASH-old
[WRN 11:48:16.503] Texture resolution is not valid for compression: '/Users/foo/Library/Application Support/Steam/steamapps/common/Kerbal Space Program/GameData/KRASH/Textures/KRASH-old.png' - consider changing the image's width and height to enable compression
[LOG 11:48:16.503] Load(Texture): KRASH/Textures/KRASH
[WRN 11:48:16.505] Texture resolution is not valid for compression: '/Users/foo/Library/Application Support/Steam/steamapps/common/Kerbal Space Program/GameData/KRASH/Textures/KRASH.png' - consider changing the image's width and height to enable compression
[LOG 11:48:16.505] Load(Texture): KRASH/Textures/KRASH_24
[LOG 11:48:16.507] Load(Texture): KRASH/Textures/Simulate
[WRN 11:48:16.509] Texture resolution is not valid for compression: '/Users/foo/Library/Application Support/Steam/steamapps/common/Kerbal Space Program/GameData/KRASH/Textures/Simulate.png' - consider changing the image's width and height to enable compression
```

Mac 10.12.6
Steam KSP 1.5.1.2335 (OSXPlayer) en-us

**Comment by linuxgurugamer** [comment]
Not relevant at all.
Please either upload the complete output_log.txt or provide a link to it

**Comment by MrJadaml** [comment]
Sorry, I have not worked with KSP mods before. I am not seeing an "output_log.txt" file is that something you can direct me to? I have the full KSP.log file here.

https://gist.github.com/MrJadaml/cadbcfa4dfb29816c85c074f529eb96b

There is also a MiniAVC.log file in the KSP directory if that helps?

**Comment by linuxgurugamer** [comment]
For the future, see this:
Read this BEFORE asking for support: http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/
which describes what people need.  I'll see if what you uploaded will be sufficient

**Comment by linuxgurugamer** [comment]
The log is showing that both the ToolbarController and the ClickThroughBlocker are not installed

**Comment by MrJadaml** [comment]
Ah, yea I was looking at the github and spaceport pages. I see now they were listed as deps in the forum page about the mod. I saw those warning though thought that MiniAVC was handling dependencies. Looks like I might need something called CKAN to manage auto dependency installations. Thank you.

Locations for deps for anyone referencing this issue in the future:
ClickThoughBlocker: https://spacedock.info/mod/1689/Click%20Through%20Blocker?ga=%253CGame+3102+%2527Kerbal+Space+Program%2527%253E

ToolbarController: https://github.com/linuxgurugamer/ToolbarControl/releases

**Comment by linuxgurugamer** [comment]
Please use the forum for support requests in the future.
Thank you
