### ISSUE TITLE
Null Simulation and Recover Craft

### ISSUE THREAD

**Issue by echoAwoo** [linuxgurugamer/KRASH#3]
It is possible to circumnavigate the simulation and treat the simulation as a real flight with 0 cost ( other than the simulation cost ? ) by landing (lithobraking is a-ok too), returning to Space Center and then recovering the craft in the tracking station or KSP Center. Exception Detector reports ~ 50 thrown exceptions per second after you do this (so it at least realizes something is up)

Win 10 Intel Core i3, lots of mods.

**Comment by linuxgurugamer** [comment]
while interesting, rather unhelpful.  A log file at the least would be useful
\
I'll try to reproduce it

**Comment by linuxgurugamer** [comment]
Oh, I see.  ok, thanks, I'll fix it.

**Comment by echoAwoo** [comment]
Sorry, I just love the mod and wanted to help contribute. I understand my information was rather useless. Is there a resource you could direct me to to help me on collecting the necessary information for you [the modders]?

**Comment by linuxgurugamer** [comment]
Problem fixed, will be in next release.
thanks

**Comment by linuxgurugamer** [comment]
Normally, the output_log.txt would be very useful.  In this case I was able to see the problem once I got into the game
You would find that file in (assuming  you are on Windows):  KSP_Data  or KSP_x64_Data, located in the main game directory.

sorry I was a bit harsh
