### ISSUE TITLE
Pushing more GUIClips than you are popping.

### ISSUE THREAD

**Issue by tivec** [linuxgurugamer/KRASH#32]
When I switch to "orbit selection" in the KRASH window, I get the following error:

![image](https://user-images.githubusercontent.com/717574/55212022-8f509500-51ee-11e9-9b65-32ff334e1e66.png)

> [EXC 06:47:30.253] NullReferenceException: Object reference not set to an instance of an object
> 	KRASH.LaunchGUI.drawSelectorWindow (Int32 id)
> 	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, Int32 instanceID, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
> [ERR 06:47:30.254] GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced)

Log file attached:
[KSP - KRASH bug report.log](https://github.com/linuxgurugamer/KRASH/files/3021314/KSP.-.KRASH.bug.report.log)

**Comment by linuxgurugamer** [comment]
Please describe your install, with regards to anything which adds launch sites:
stock game
Expansion/dlc
Kopernicus,

etc.
Thank you

**Comment by linuxgurugamer** [comment]
If no response soon, I'm going to close this
