### ISSUE TITLE
1.9.1 compatibility

### ISSUE THREAD

**Issue by sushicw** [linuxgurugamer/KRASH#34]
Will this mod be updated for 1.9.1 compatibility? What work is needed?

**Comment by linuxgurugamer** [comment]
1.  would be preferable to ask questions like this on the forums, this is for issues
2.  If you had looked on the forums, you would have gotten your answer
3.  Most mods compatible with 1.8 will work on 1.9 without any problems.

and in answer to your question, it works on 1.9.1 without any update needed
