### ISSUE TITLE
KRASH issues with Principia?

### ISSUE THREAD

**Issue by uriyuzhui** [linuxgurugamer/KRASH#37]
Hi,

Not sure if this is just me since I didn't find any other report/complaint online, but my KRASH does not seem to go along well with Principia. I have a RP-1 essential setup for my KSP 1.8.1 with a bunch of mods, including but not limited to:

- KRASH (0.5.33, latest)
- Principia (Gallai, latest)
- etc.

And I encountered a wide range of issues, to show a few examples:

1. Incorrect teleportation destination when using "landed" setup
https://www.youtube.com/watch?v=ggSFkYqyBtI

2. Drifting orbit (1:05) when using "orbit" setup, and strange ground movement inconsistent with HUD/MJ readouts (4:19)
https://www.youtube.com/watch?v=56Lg8Qs11ao

3. Another strange ground movement under "landed" setup and sudden attitude change (0:41)
https://www.youtube.com/watch?v=FWfFJIs7aag

4. Another incorrect teleportation destination (underground) caused immediate explosion
https://www.youtube.com/watch?v=RWv-GGUxeW4

I noticed that these physics issues only exist when under simulation mode. Actual flights seem to work fine.

**Comment by linuxgurugamer** [comment]
Sorry, but I don't support Principia.  It's too far outside the norms, and yes, you are the first person to mention any issue

**Comment by uriyuzhui** [comment]
Appreciate the fast response, and I think it's helpful at least to confirm that these issues are expected to an extend.

One solution I just discovered today regarding the strange surface movement:
1. Alt+F12 and open the cheat menu anytime during a KRASH simulation
2. Use the cheat to set an orbit - literally anything. Principia will pull you back to where you were instantly afterward.
3. However, after the cheat set-orbit being undone by Principia, the strange ground movement halted.

I guess this is caused due to the conflict between stock and Principia's own movement systems. @linuxgurugamer if not a big effort, maybe in the future you could implement an invocation to the cheat's set-orbit function after KRASH teleportation. 

Anyway, hopefully this could help someone else who has the same issue.
