### ISSUE TITLE
Liquid Fuel engines not firing in simulation

### ISSUE THREAD

**Issue by jwwolff** [linuxgurugamer/KRASH#44]
The liquid fuel engines not working during simulation even though they are activated. Tried multiple ships and had the same problem though solid rocket boosters still work fine. Though when brought out to the launch pad and launched the rockets work correctly. My assumption is that it is a mod compatibility problem as I added a couple of mods and this problem occurred. If I can help in any way let me know. (its not crashing so I don't know if a log would help)

I am using game version 1.11 on Mac.

A list of install mods:
KSP: 1.11 (Unix) - Unity: 2019.2.2f1 - OS: Mac OS X 10.16.0
000_AT_Utils - 1.9.6
ClickThroughBlocker - 0.1.10.15
Filter Extensions - 3.2.6
Toolbar - 1.8.0.5
USI Tools - 1.4
ToolbarControl - 0.1.9.4
Astrogator - 0.10.2
B9 Part Switch - 2.17
BetterLoadSaveGame - 2.5.2.1
Camera Focus Changer - 1.1
Chatterer - 0.9.99.2788
Community Category Kit - 5.2
Community Resource Pack - 1.4.2
CommunityTechTree - 3.4.3
Connected Living Space - 2.0.0.6
Contract Configurator - 1.30.5
Contract Pack: Field Research - 1.2.2
Contract Pack: Bases and Stations - 3.7.2.4
Contract Pack: RemoteTech - 2.1.4
Contract Pack: Tourism Plus - 1.5.2
CrewRandR - 1.1.11
CryoEngines - 2.0.1
CryoTanks - 1.6
DatedQuickSaves - 1.2.4.4
DeployableEngines - 1.3
DynamicBatteryStorage - 2.2.2
Easy Vessel Switch - 2.2.7689.40431
FarFutureTechnologies - 1.1.2
Ferram Aerospace Research - 0.16.0.1
Firespitter - 7.17
GravityTurn - 1.8.1.4
GroundConstruction - 2.6.4.1
HeatControl - 0.6
RasterPropMonitor - 0.31.4
JanitorsCloset - 0.3.7.6
KRASH - 0.5.33.3
KSP-AVC Plugin - 1.4.1.5
KerbalAtomics - 1.2.1
Kerbal Construction Time - 1.4.9
Kerbal Engineer Redux - 1.1.8.3
Kerbal Joint Reinforcement - 4.1.15
LoadingTipsPlus - 1.9
MagiCore - 1.3.2.3
MarkIVSystem - 3.2
MechJebForAll - 1.3.0.6
MoarFilterExtensionConfigs - 1.0.5.2
ModularFlightIntegrator - 1.2.10
Docking Port Alignment Indicator - 6.9.2.2
NearFutureAeronautics - 2.1
NearFutureConstruction - 1.3.1
NearFutureElectrical - 1.2.2
NearFutureExploration - 1.1.1
NearFutureLaunchVehicles - 2.1.3
NearFutureProps - 0.6.4
NearFuturePropulsion - 1.3.2
NearFutureSolar - 1.3.1
NearFutureSpacecraft - 1.4.1
Final Frontier - 1.10.0.3485
Precise Node - 1.2.11.1
ReStock - 1.3
ReStockPlus - 1.3
RealPlume - Stock - 4.0.6
RemoteTech - 1.9.10
SCANsat - 1.20.4
SafeChute - 2.1.20
ScienceAlert - 1.9.8.9
ShowFPS - 0.2.4
SpaceDust - 0.3.3
ButtonManager - 0.0.1
SpaceTuxLibrary - 0.0.6
VesselModuleSave - 0.0.1.1
StageRecovery - 1.9.5.1
StationPartsExpansionRedux - 1.4
SystemHeat - 0.3.10
TAC Fuel Balancer - 2.21.5.1
TextureReplacer - 4.3.1
ThrottleControlledAvionics - 3.7.2
Trajectories - 2.4
Kerbal Alarm Clock - 3.13
USI Core - 1.4
Konstruction - 1.4
USI-LS - 1.4
MKS - 1.4.1
Waterfall - 0.6.2
Waypoint Manager - 2.8.2.7
Kerbal Actuators - 1.8.3.1
ZeroMiniAVC - 1.1.0.1

**Comment by linuxgurugamer** [comment]
You are correct in that it has to be a mod compatibility problem.  Your first place to post should the the forums, especially if you suspect this, because there are a lot of other people on the forums who can help, and I don't have time to test against every mod.  It might also be a bad install.
Please post this in the KRASH thread on the forum, and don't forget to include a link to the Player.Log file for analysis

**Comment by jwwolff** [comment]
Ok thanks

**Comment by jwwolff** [comment]
I did more testing I think that its actually the GravityTurn mod my bad.

**Comment by jwwolff** [comment]
I did a little more testing and reproduced the problem outside of KRASH so now I don't know what's causing it but some times it works perfectly fine. :( Sorry for wasting your time
