### ISSUE TITLE
Integration with "EVARepair" made by Angel-125

### ISSUE THREAD

**Issue by Araym-KSP** [linuxgurugamer/KRASH#49]
I generally expected, by using past failure mods, that KRASH could sort of override them during a career.

Lately, with the development of the new "EVARepair", that is not happening anymore when this mod is installed to manage thefailure and repairs...
... quite obviously, being a very recent mod.

It will be lovely to have both integrated as expected.

**Comment by linuxgurugamer** [comment]
Meaning what, that failures are still happening?  You will need to contact Angel-125 about checking for KRASH being active, nothing I can do about it.

There is an API he can interface with
