### ISSUE TITLE
Massive performance impact during Sim

### ISSUE THREAD

**Issue by mblob** [linuxgurugamer/KRASH#5]
Even if https://github.com/linuxgurugamer/KRASH/issues/4 got fixed. There is still a huge performance impact when inside a sim.
When launching a sim the MET is going straight to orange, bright green when in normal flight.
Fps is cut by half.

I don't see anything informational in the debug window.
I there is any way i can help you identify the problem ... let me know wht i can do.

My setup is heavily modded, I'll try to see if its related to other mod and keep you updated.,

**Comment by linuxgurugamer** [comment]
There shouldn't be any performance impact at all during a sip.  All it's doing is keeping track of the costs, and that is miniscule.
If you can't figure it out, please do the following two things:
1.  Send me the save file, i'll see if I can replicate it
2.  Create a new install, only install KRASH and see how it works there.

**Comment by linuxgurugamer** [comment]
Fixed
