### ISSUE TITLE
Simulation Begins with Pause Menu Open

### ISSUE THREAD

**Issue by echoAwoo** [linuxgurugamer/KRASH#6]
Sorry no output, game did not produce one from this. This one popped up on the update today. 

Starting a simulation opens the KRASH modified pause menu. Tapping ESC unpauses the game but the menu does not disappear. It is unable to be moved, while paused or unpaused, but can be interacted with. Other than possibly accidentally interacting with the window, it does not interfere with the ability to run a simulation.

**Comment by echoAwoo** [comment]
It appears to cause this issue even if you aren't simulating it.

**Comment by linuxgurugamer** [comment]
That sounds like a possibly corrupted file.  Please do the following:
Open the persistent.sfs file in an editor, and find the following section:

```
SCENARIO
{
    name = KRASHPersistent
    scene = 5, 6, 7, 8
    shelterSimulationActive = False
    selectedCostsCfg = * Normal
}
```

Delete it, save and try the game again.  Let me know if it still happens.

**Comment by echoAwoo** [comment]
It was under a new save when it happened. I went into the persistent.sfs and deleted the entry. I will try on that save again and try on a new save and see if I can't reproduce it again.

**Comment by linuxgurugamer** [comment]
If no new data, I'll close this in a day or so

**Comment by echoAwoo** [comment]
Close sorry i couldn't reproduce again

**Comment by linuxgurugamer** [comment]
ok, thanks.  Let me know if it happens again

**Comment by echoAwoo** [comment]
I believe I've found the cause of the issue.

When you select the option to limit max cost in game, it changes the value under the field selectedCostsCfg from "\* Normal" to "\* Custom", correct? I believe that's why deleting that section works since it re-adds it with the correct value. Changing this value to the default "\* Normal" should correct it then? 

It seems there are two possible symptoms of this bug, either camera locks at view  (~30m right,3m down, 5m back from the vessel) on simulation, or Pause Menu gets stuck open

**Comment by linuxgurugamer** [comment]
So you are changing the config values?
You are putting in a value in the Default Max Sim Cost?

**Comment by linuxgurugamer** [comment]
Are you doing this in the config window, or editing the file?

**Comment by linuxgurugamer** [comment]
With the current version, I see that the max sim cost isn't being honored (ie: sim costs go higher).  Can you try with the current version?  If it still happens, please send me the save file and the KRASH directory zipped up, thanks

**Comment by linuxgurugamer** [comment]
FYI, max allowable sim cost wasn't being used

**Comment by linuxgurugamer** [comment]
I think te problem is that you ran out of cash?

**Comment by echoAwoo** [comment]
Config Window causes it, but it's a check-uncheck that causes it. I haven't been able to reproduce it with it On, or with it off by default. But when I turn it on, then turn it off it comes up like this.

**Comment by linuxgurugamer** [comment]
I was just able to replicate this.  It's tied in with another bug in the config stuff

**Comment by echoAwoo** [comment]
Awesome glad I'm not crazy :+1: . If I notice anything else about it I'll report. Thanks!

**Comment by linuxgurugamer** [comment]
I think I got it.  Turned out I didn't replicate, but did find another which seems like it was related.
Can you try this beta and let me know:  https://www.dropbox.com/s/xfnk89c8xxlmx2r/krash-beta.zip?dl=0
it will replace the entire directory.  Please delete the old directory, file locations have been moved

**Comment by dtondo** [comment]
I still got this error on the last version... I tried the dropbox nevertheless the link returned 404 error.

**Comment by linuxgurugamer** [comment]
Please try the latest release (0.5.18.1) and let me know how it goes

**Comment by dtondo** [comment]
Hi linuxgurugamer,

First of all thank you for working on this issue.

When tested on sandbox it worded well. Nevertheless I was able to reproduce it in carrer mode even using the last version as suggested:
![ckan](https://cloud.githubusercontent.com/assets/5522566/16571498/bc261b72-4233-11e6-90bf-3ee1383b5149.png)

Also I recorded a video for you. Would you mind to take a look?:
https://youtu.be/Y19JJycXyvQ

If you need I can send files from you, here is the plugin folder:
https://www.dropbox.com/s/xsoic60t4499qsj/KRASH.zip?dl=0

With kind regards,
Douglas Tondo

**Comment by linuxgurugamer** [comment]
video is great, thanks.  Please leave it up.  I don't have time to look at this right now, but will get to it in the next few days

**Comment by dtondo** [comment]
Hi linuxgurugamer,

Sure, It is on youtube, no worries :)

With kind regards,
Douglas Tondo

**Comment by dtondo** [comment]
Hi linuxgurugamer,

Sure, It is on youtube, no worries :)

With kind regards,
Douglas Tondo
